# Generated by Django 4.2.19 on 2025-03-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend.api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
