# Generated by Django 4.2.19 on 2025-04-06 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_barber_address_barber_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='backend.api.barber'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('barber', 'name')},
        ),
        migrations.DeleteModel(
            name='BarberService',
        ),

    ]
