# Generated by Django 4.2.19 on 2025-04-07 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend.api', '0005_alter_service_options_service_barber_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='service',
            name='barber',
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='backend.api.barber')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.api.service')),
            ],
            options={
                'ordering': ['service__name'],
                'unique_together': {('barber', 'service')},
            },
        ),
    ]
