# Generated by Django 4.2.19 on 2025-04-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend.api', '0007_alter_barberservice_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barberservice',
            old_name='price',
            new_name='price_adjustment',
        ),
    ]
