# Generated by Django 4.2.19 on 2025-05-03 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_price_barberservice_price_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberportfolio',
            name='group',
        ),
        migrations.AddField(
            model_name='barberportfolio',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barberportfolio',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_images', to='backend.api.barberportfolio'),
        ),
        migrations.DeleteModel(
            name='PortfolioGroup',
        ),
    ]
