# Generated by Django 4.2.19 on 2025-06-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend.api', '0010_remove_appointment_status_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
