# Generated by Django 4.2.19 on 2025-07-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_appointment_status_alter_barber_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="barber",
            name="pause_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="barber",
            name="pause_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="barber",
            name="pause_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
