# Generated by Django 4.2.19 on 2025-07-15 22:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barber",
            fields=[
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
            ],
        ),
        migrations.CreateModel(
            name="BarberPortfolio",
            fields=[
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
            ],
            options={
                "ordering": ["-date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
            ],
            options={
                "ordering": ["day", "start_time"],
                "unique_together": {("barber", "day")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("customer", "appointment")},
            },
        ),
        migrations.CreateModel(
            name="BarberService",
            fields=[
            ],
            options={
                "ordering": ["service__name"],
                "unique_together": {("barber", "service")},
            },
        ),
    ]
