# Generated by Django 4.2.19 on 2025-04-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_portfoliogroup_barberportfolio_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='barber',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barber',
            name='price_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='price_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='barber_profiles/'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
