# Generated by Django 4.2.19 on 2025-04-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_price_service_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
